// <auto-generated />
using System;
using APSPA_BakendAndFrontend.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APSPA_BakendAndFrontend.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APSPA_BakendAndFrontend.Server.model.ActivityRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActivityDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activity_date");

                    b.Property<int>("ActivityDurationMin")
                        .HasColumnType("integer")
                        .HasColumnName("activity_duration_min");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("activity_type");

                    b.Property<int?>("CaloriesBurned")
                        .HasColumnType("integer")
                        .HasColumnName("calories_burned");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PerceivedIntensity")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("perceived_intensity");

                    b.Property<int?>("RecoveryScore")
                        .HasColumnType("integer")
                        .HasColumnName("recovery_score");

                    b.Property<int?>("RestingHeartRate")
                        .HasColumnType("integer")
                        .HasColumnName("resting_heart_rate");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("activity_records", (string)null);
                });

            modelBuilder.Entity("APSPA_BakendAndFrontend.Server.model.AiModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_name");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_version");

                    b.Property<string>("TargetMetric")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_metric");

                    b.HasKey("Id");

                    b.ToTable("ai_models", (string)null);
                });

            modelBuilder.Entity("APSPA_BakendAndFrontend.Server.model.AiRequestLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("endpoint");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("http_method");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("is_success");

                    b.Property<int>("PredictionId")
                        .HasColumnType("integer")
                        .HasColumnName("prediction_id");

                    b.Property<string>("RequestPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("request_payload");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_payload");

                    b.Property<int?>("ResponseStatus")
                        .HasColumnType("integer")
                        .HasColumnName("response_status");

                    b.HasKey("Id");

                    b.HasIndex("PredictionId");

                    b.ToTable("ai_request_logs", (string)null);
                });

            modelBuilder.Entity("APSPA_BakendAndFrontend.Server.model.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("APSPA_BakendAndFrontend.Server.model.Prediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("activity_record_id");

                    b.Property<int?>("AiModelId")
                        .HasColumnType("integer")
                        .HasColumnName("ai_model_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("EffortScore")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("effort_score");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<decimal?>("FatigueRiskScore")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("fatigue_risk_score");

                    b.Property<decimal?>("PredictedAvgHeartRate")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("predicted_avg_heart_rate");

                    b.Property<string>("PredictionStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("prediction_status");

                    b.Property<string>("RawInputPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_input_payload");

                    b.Property<string>("RawOutputPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_output_payload");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ActivityRecordId");

                    b.HasIndex("AiModelId");

                    b.HasIndex("UserId");

                    b.ToTable("predictions", (string)null);
                });

            modelBuilder.Entity("APSPA_BakendAndFrontend.Server.model.Recommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int>("PredictionId")
                        .HasColumnType("integer")
                        .HasColumnName("prediction_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("PredictionId");

                    b.ToTable("recommendations", (string)null);
                });

            modelBuilder.Entity("APSPA_BakendAndFrontend.Server.model.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("APSPA_BakendAndFrontend.Server.model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("height_cm");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("APSPA_BakendAndFrontend.Server.model.UserHealthProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BMI")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("bmi");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<int?>("RecoveryScore")
                        .HasColumnType("integer")
                        .HasColumnName("recovery_score");

                    b.Property<int?>("RestingHeartRate")
                        .HasColumnType("integer")
                        .HasColumnName("resting_heart_rate");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_health_profiles", (string)null);
                });

            modelBuilder.Entity("APSPA_BakendAndFrontend.Server.model.ActivityRecord", b =>
                {
                    b.HasOne("APSPA_BakendAndFrontend.Server.model.User", "User")
                        .WithMany("ActivityRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("APSPA_BakendAndFrontend.Server.model.AiRequestLog", b =>
                {
                    b.HasOne("APSPA_BakendAndFrontend.Server.model.Prediction", "Prediction")
                        .WithMany("AiRequestLogs")
                        .HasForeignKey("PredictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prediction");
                });

            modelBuilder.Entity("APSPA_BakendAndFrontend.Server.model.AuditLog", b =>
                {
                    b.HasOne("APSPA_BakendAndFrontend.Server.model.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("APSPA_BakendAndFrontend.Server.model.Prediction", b =>
                {
                    b.HasOne("APSPA_BakendAndFrontend.Server.model.ActivityRecord", "ActivityRecord")
                        .WithMany("Predictions")
                        .HasForeignKey("ActivityRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APSPA_BakendAndFrontend.Server.model.AiModel", "AiModel")
                        .WithMany("Predictions")
                        .HasForeignKey("AiModelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("APSPA_BakendAndFrontend.Server.model.User", "User")
                        .WithMany("Predictions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityRecord");

                    b.Navigation("AiModel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APSPA_BakendAndFrontend.Server.model.Recommendation", b =>
                {
                    b.HasOne("APSPA_BakendAndFrontend.Server.model.Prediction", "Prediction")
                        .WithMany("Recommendations")
                        .HasForeignKey("PredictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prediction");
                });

            modelBuilder.Entity("APSPA_BakendAndFrontend.Server.model.RefreshToken", b =>
                {
                    b.HasOne("APSPA_BakendAndFrontend.Server.model.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("APSPA_BakendAndFrontend.Server.model.UserHealthProfile", b =>
                {
                    b.HasOne("APSPA_BakendAndFrontend.Server.model.User", "User")
                        .WithMany("UserHealthProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("APSPA_BakendAndFrontend.Server.model.ActivityRecord", b =>
                {
                    b.Navigation("Predictions");
                });

            modelBuilder.Entity("APSPA_BakendAndFrontend.Server.model.AiModel", b =>
                {
                    b.Navigation("Predictions");
                });

            modelBuilder.Entity("APSPA_BakendAndFrontend.Server.model.Prediction", b =>
                {
                    b.Navigation("AiRequestLogs");

                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("APSPA_BakendAndFrontend.Server.model.User", b =>
                {
                    b.Navigation("ActivityRecords");

                    b.Navigation("AuditLogs");

                    b.Navigation("Predictions");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserHealthProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
